float TERMBOX_MARGIN_LEFT = 15;
float TERMBOX_MARGIN_RIGHT = 5;
float TERMBOX_MARGIN_LR = TERMBOX_MARGIN_LEFT + TERMBOX_MARGIN_RIGHT;

float DASHEDBOX_MARGIN = 5;
float DASHED_ON_INTERVAL = 4;
float DASHED_OFF_INTERVAL = 3;

float NAME_MARGIN_HALF = 2.5;

float TEST_MARGIN_LR = 10;

int TEXT_SIZE_SMALL = 10;
int TEXT_SIZE_DEFAULT = 12;

float CENTER_Y = 300;

float CROSS_MARGIN = 20;
float CROSS_PADDING_HALF = 2.5;
