float TERM_MARGIN_LEFT = 15;
float TERM_MARGIN_RIGHT = 5;
float TERM_MARGIN_LR = TERM_MARGIN_LEFT + TERM_MARGIN_RIGHT;
float TERM_MARGIN_BOTTOM = 2.5;       // == TermMarginTop

float TEST_MARGIN_LR = 10;

int TEXT_SIZE_SMALL = 10;
int TEXT_SIZE_DEFAULT = 12;
